; GAMEBGM, AKG format, v1.0.

; Generated by Arkos Tracker 2.

GAMEBGM_Start
GAMEBGM_StartDisarkGenerateExternalLabel

GAMEBGM_DisarkByteRegionStart0
	db "AT20"
GAMEBGM_DisarkPointerRegionStart1
	dw GAMEBGM_ArpeggioTable	; The address of the Arpeggio table.
	dw GAMEBGM_PitchTable	; The address of the Pitch table.
	dw GAMEBGM_InstrumentTable	; The address of the Instrument table.
	dw GAMEBGM_EffectBlockTable	; The address of the Effect Block table.
GAMEBGM_DisarkPointerRegionEnd1


; The addresses of each Subsong:
GAMEBGM_DisarkPointerRegionStart2
	dw GAMEBGM_Subsong0_Start
GAMEBGM_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
GAMEBGM_ArpeggioTable
GAMEBGM_DisarkPointerRegionStart3
GAMEBGM_DisarkPointerRegionEnd3

; Declares all the Pitches.
GAMEBGM_PitchTable
GAMEBGM_DisarkPointerRegionStart4
GAMEBGM_DisarkPointerRegionEnd4

; Declares all the Instruments.
GAMEBGM_InstrumentTable
GAMEBGM_DisarkPointerRegionStart5
	dw GAMEBGM_EmptyInstrument
	dw GAMEBGM_Instrument1
	dw GAMEBGM_Instrument2
	dw GAMEBGM_Instrument3
	dw GAMEBGM_Instrument4
GAMEBGM_DisarkPointerRegionEnd5

GAMEBGM_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
GAMEBGM_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

GAMEBGM_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 81	; Soft only. Volume: 10.
	db 5	; Additional data. Noise: 5. Pitch? false. Arp? false. Period? false.

	db 73	; Soft only. Volume: 9.
	db 36	; Additional data. Noise: 4. Pitch? true. Arp? false. Period? false.
	dw 16	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 35	; Additional data. Noise: 3. Pitch? true. Arp? false. Period? false.
	dw 32	; Pitch.

	db 57	; Soft only. Volume: 7.
	db 34	; Additional data. Noise: 2. Pitch? true. Arp? false. Period? false.
	dw 48	; Pitch.

	db 49	; Soft only. Volume: 6.
	db 33	; Additional data. Noise: 1. Pitch? true. Arp? false. Period? false.
	dw 64	; Pitch.

	db 41	; Soft only. Volume: 5.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 80	; Pitch.

	db 33	; Soft only. Volume: 4.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 96	; Pitch.

	db 25	; Soft only. Volume: 3.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 112	; Pitch.

	db 6	; Loop to silence.

GAMEBGM_Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 209	; Soft only. Volume: 10. Volume only.

	db 73	; Soft only. Volume: 9.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 32	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 64	; Pitch.

	db 57	; Soft only. Volume: 7.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 96	; Pitch.

	db 49	; Soft only. Volume: 6.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 128	; Pitch.

	db 41	; Soft only. Volume: 5.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 160	; Pitch.

	db 33	; Soft only. Volume: 4.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 192	; Pitch.

	db 25	; Soft only. Volume: 3.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 224	; Pitch.

	db 6	; Loop to silence.

GAMEBGM_Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 225	; Soft only. Volume: 12. Volume only.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 217	; Soft only. Volume: 11. Volume only.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 201	; Soft only. Volume: 9. Volume only.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 193	; Soft only. Volume: 8. Volume only.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 177	; Soft only. Volume: 6. Volume only.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 41	; Soft only. Volume: 5.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 169	; Soft only. Volume: 5. Volume only.

	db 6	; Loop to silence.

GAMEBGM_Instrument4
	db 2	; The speed (>0, 0 for 256).
	db 225	; Soft only. Volume: 12. Volume only.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -1	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -2	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 2	; Arpeggio.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -3	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 1	; Arpeggio.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -4	; Arpeggio.

	db 177	; Soft only. Volume: 6. Volume only.

	db 41	; Soft only. Volume: 5.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -5	; Arpeggio.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -1	; Arpeggio.

	db 25	; Soft only. Volume: 3.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -6	; Arpeggio.

	db 17	; Soft only. Volume: 2.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -2	; Arpeggio.

	db 9	; Soft only. Volume: 1.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -7	; Arpeggio.

	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
GAMEBGM_EffectBlockTable

GAMEBGM_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
GAMEBGM_Subsong0_DisarkByteRegionStart0
GAMEBGM_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 1	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 2	; Loop start index (>=0).
	db 6	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 0	; Base note index (>=0).

GAMEBGM_Subsong0_Linker
GAMEBGM_Subsong0_DisarkPointerRegionStart1
; Position 0
	dw GAMEBGM_Subsong0_Track0
	dw GAMEBGM_Subsong0_Track1
	dw GAMEBGM_Subsong0_Track0
	dw GAMEBGM_Subsong0_LinkerBlock0

; Position 1
	dw GAMEBGM_Subsong0_Track0
	dw GAMEBGM_Subsong0_Track1
	dw GAMEBGM_Subsong0_Track0
	dw GAMEBGM_Subsong0_LinkerBlock0

; Position 2
GAMEBGM_Subsong0_Linker_Loop
	dw GAMEBGM_Subsong0_Track0
	dw GAMEBGM_Subsong0_Track1
	dw GAMEBGM_Subsong0_Track2
	dw GAMEBGM_Subsong0_LinkerBlock1

; Position 3
	dw GAMEBGM_Subsong0_Track0
	dw GAMEBGM_Subsong0_Track1
	dw GAMEBGM_Subsong0_Track2
	dw GAMEBGM_Subsong0_LinkerBlock1

; Position 4
	dw GAMEBGM_Subsong0_Track0
	dw GAMEBGM_Subsong0_Track1
	dw GAMEBGM_Subsong0_Track2
	dw GAMEBGM_Subsong0_LinkerBlock1

; Position 5
	dw GAMEBGM_Subsong0_Track0
	dw GAMEBGM_Subsong0_Track3
	dw GAMEBGM_Subsong0_Track4
	dw GAMEBGM_Subsong0_LinkerBlock1

; Position 6
	dw GAMEBGM_Subsong0_Track0
	dw GAMEBGM_Subsong0_Track1
	dw GAMEBGM_Subsong0_Track5
	dw GAMEBGM_Subsong0_LinkerBlock1

GAMEBGM_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
GAMEBGM_Subsong0_DisarkWordForceReference2
	dw GAMEBGM_Subsong0_Linker_Loop

GAMEBGM_Subsong0_LinkerBlock0
	db 16	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
GAMEBGM_Subsong0_DisarkWordForceReference3
	dw GAMEBGM_Subsong0_SpeedTrack0	; SpeedTrack address.
GAMEBGM_Subsong0_DisarkWordForceReference4
	dw GAMEBGM_Subsong0_EventTrack0	; EventTrack address.
GAMEBGM_Subsong0_LinkerBlock1
	db 32	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
GAMEBGM_Subsong0_DisarkWordForceReference5
	dw GAMEBGM_Subsong0_SpeedTrack0	; SpeedTrack address.
GAMEBGM_Subsong0_DisarkWordForceReference6
	dw GAMEBGM_Subsong0_EventTrack0	; EventTrack address.

GAMEBGM_Subsong0_Track0
	db 61, 127	; Waits for 128 lines.


GAMEBGM_Subsong0_Track1
	db 164
	db 2	; New Instrument (2).
	db 36
	db 36
	db 36
	db 176
	db 1	; New Instrument (1).
	db 164
	db 2	; New Instrument (2).
	db 36
	db 36
	db 36
	db 176
	db 1	; New Instrument (1).
	db 164
	db 2	; New Instrument (2).
	db 36
	db 176
	db 1	; New Instrument (1).
	db 164
	db 2	; New Instrument (2).
	db 36
	db 36
	db 36
	db 36
	db 36
	db 36
	db 176
	db 1	; New Instrument (1).
	db 164
	db 2	; New Instrument (2).
	db 36
	db 36
	db 36
	db 176
	db 1	; New Instrument (1).
	db 164
	db 2	; New Instrument (2).
	db 36
	db 176
	db 1	; New Instrument (1).
	db 164
	db 2	; New Instrument (2).
	db 36
	db 36
	db 61, 127	; Waits for 128 lines.


GAMEBGM_Subsong0_Track2
	db 173
	db 3	; New Instrument (3).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


GAMEBGM_Subsong0_Track3
	db 164
	db 2	; New Instrument (2).
	db 36
	db 36
	db 36
	db 176
	db 1	; New Instrument (1).
	db 164
	db 2	; New Instrument (2).
	db 36
	db 36
	db 36
	db 176
	db 1	; New Instrument (1).
	db 164
	db 2	; New Instrument (2).
	db 36
	db 176
	db 1	; New Instrument (1).
	db 164
	db 2	; New Instrument (2).
	db 36
	db 36
	db 36
	db 36
	db 36
	db 36
	db 176
	db 1	; New Instrument (1).
	db 164
	db 2	; New Instrument (2).
	db 36
	db 36
	db 48
	db 48
	db 48
	db 48
	db 43
	db 43
	db 43
	db 43
	db 61, 127	; Waits for 128 lines.


GAMEBGM_Subsong0_Track4
	db 173
	db 3	; New Instrument (3).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 48
	db 61, 127	; Waits for 128 lines.


GAMEBGM_Subsong0_Track5
	db 176
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 48
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 50
	db 48
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 47
	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 173
	db 4	; New Instrument (4).
	db 61, 127	; Waits for 128 lines.


; The speed tracks
GAMEBGM_Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
GAMEBGM_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

GAMEBGM_Subsong0_DisarkByteRegionEnd0
