; Sound Effects for song Sound, version 2.0, generated by Arkos Tracker 2.

SoundEffects
SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
SoundEffectsDisarkPointerRegionStart0
	dw SoundEffects_Sound1	; Sound effect 1.
	dw SoundEffects_Sound2	; Sound effect 2.
	dw SoundEffects_Sound3	; Sound effect 3.
	dw SoundEffects_Sound4	; Sound effect 4.
SoundEffectsDisarkPointerRegionEnd0

SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
SoundEffects_Sound1
	db 0	; Speed

SoundEffects_Sound1_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 212	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 193	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 220	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 201	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 244	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 225	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 252	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 256	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 260	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 264	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 268	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 272	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 276	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 280	; Software period.

	db 5	; Soft only. Volume: 1.
	dw 284	; Software period.

	db 4	; End of the sound effect.

; Sound effect 2.
SoundEffects_Sound2
	db 1	; Speed

SoundEffects_Sound2_Loop	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 42	; Software period.

	db 169	; Soft only. Volume: 10.
	db 1	; Noise: 1.
	dw 42	; Software period.

	db 161	; Soft only. Volume: 8.
	db 1	; Noise: 1.
	dw 42	; Software period.

	db 153	; Soft only. Volume: 6.
	db 1	; Noise: 1.
	dw 42	; Software period.

	db 145	; Soft only. Volume: 4.
	db 1	; Noise: 1.
	dw 42	; Software period.

	db 137	; Soft only. Volume: 2.
	db 1	; Noise: 1.
	dw 42	; Software period.

	db 4	; End of the sound effect.

; Sound effect 3.
SoundEffects_Sound3
	db 3	; Speed

SoundEffects_Sound3_Loop	db 248	; No soft, no hard. Volume: 15.
	db 3	; Noise: 3.

	db 224	; No soft, no hard. Volume: 12.
	db 26	; Noise: 26.

	db 200	; No soft, no hard. Volume: 9.
	db 26	; Noise: 26.

	db 176	; No soft, no hard. Volume: 6.
	db 31	; Noise: 31.

	db 144	; No soft, no hard. Volume: 2.
	db 31	; Noise: 31.

	db 4	; End of the sound effect.

; Sound effect 4.
SoundEffects_Sound4
	db 7	; Speed

SoundEffects_Sound4_Loop	db 248	; No soft, no hard. Volume: 15.
	db 31	; Noise: 31.

	db 232	; No soft, no hard. Volume: 13.
	db 31	; Noise: 31.

	db 216	; No soft, no hard. Volume: 11.
	db 31	; Noise: 31.

	db 200	; No soft, no hard. Volume: 9.
	db 31	; Noise: 31.

	db 184	; No soft, no hard. Volume: 7.
	db 31	; Noise: 31.

	db 168	; No soft, no hard. Volume: 5.
	db 31	; Noise: 31.

	db 144	; No soft, no hard. Volume: 2.
	db 31	; Noise: 31.

	db 136	; No soft, no hard. Volume: 1.
	db 31	; Noise: 31.

	db 4	; End of the sound effect.

SoundEffectsDisarkByteRegionEnd1
